#! /bin/sh
sxhkd &
xsetroot -cursor_name left_ptr
picom -b
wal -R &
$HOME/.config/polybar/launch.sh
. "${HOME}/.cache/wal/colors.sh"


#bspc monitor eDP1 -d I II III IV
#bspc monitor DP-2-2 -d V VI VII VIII
#bspc monitor -d  一   二   三   四 
#bspc monitor eDP1 -d  一   二   三   四 
#bspc monitor DP2-2 -d  五   六   七   八 
#bspc monitor DP2-1 -d  九   十 

screens=($(bspc query -M --names | tr " " "\n"))

case ${#screens[@]} in
	1) bspc monitor -d " I " II III IV;;
	2)
		bspc monitor ${screens[0]} -d " I "
		bspc monitor ${screens[1]} -d " II " III IV
		;;
	3)
		bspc monitor ${screens[0]} -d " I "
		bspc monitor ${screens[1]} -d " II " III
		bspc monitor ${screens[2]} -d " IV "
		;;
	*) bspc monitor -d " I " II III IV;;
esac

bspc config border_width		8
bspc config window_gap			8
bspc config top_padding			0

bspc config split_ratio			0.50
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config focus_follows_pointer	true

bspc config normal_border_color 	"$color0"
bspc config active_border_color 	"$color1"
bspc config focused_border_color 	"$color1"
bspc config presel_feedback_color	"$color1"
